const actionTypes = {
    "CAN_CASTLE": "CAN_CASTLE",
    "CLEAR_CANDIDATE_MOVES": "CLEAR_CANDIDATE_MOVES",
    "GENERATE_CANDIDATE_MOVES": "GENERATE_CANDIDATE_MOVES",
    "NEW_MOVE": "NEW_MOVE",
    "NEW_GAME": "NEW_GAME",
    "PROMOTION_CLOSE": "PROMOTION_CLOSE",
    "PROMOTION_OPEN": "PROMOTION_OPEN",
    "STALEMATE": "STALEMATE",
    "INSUFFICIENT_MATERIAL": "INSUFFICIENT_MATERIAL",
    "WIN": "WIN",
    "FIRST_MOVE": "FIRST_MOVE",
    "PREVIOUS_MOVE": "PREVIOUS_MOVE",
    "NEXT_MOVE": "NEXT_MOVE",
    "CURRENT_MOVE": "CURRENT_MOVE",
    "INCREMENT_STRIKES": "INCREMENT_STRIKES",
    "LOGIN": "LOGIN",
    "LOGOUT": "LOGOUT",
    "SET_LINES": "SET_LINES",
    "TOGGLE_SELECTED_LINE_IDX": "TOGGLE_SELECTED_LINE_IDX",
    "SET_SELECTED_LINES": "SET_SELECTED_LINES",
    "NEXT_MOVE": "NEXT_MOVE"
}

export default actionTypes
